spring.application.name=practicebeforesecurity
spring.datasource.url=jdbc:mysql://localhost:3306/todolistUpdate
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8085


# Nivel global (para todo)
logging.level.root=INFO

# Tus clases / aspectos
logging.level.com.querywithapi=TRACE

# Spring Security
logging.level.org.springframework.security=DEBUG

# Hibernate (opcional)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Actuator: expone health e info
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
# Metadata opcional para /actuator/info
info.app.name=practicebeforesecurity
info.app.description=Proyecto de prueba para Swagger + Actuator
info.app.contact=tu-email@ejemplo.com

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
# (opcional) limita qué rutas documentar: springdoc.paths-to-match=/api/**